// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetTheme():Promise<string>;

export function SetTheme(arg1:string):Promise<void>;

export function VerifyLogin(arg1:string,arg2:string):Promise<Record<string, any>>;
