// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function VerifyLogin(arg1, arg2) {
  return window['go']['main']['App']['VerifyLogin'](arg1, arg2);
}
