import {
  mdiAccount,
  mdiAccountMultiple,
  mdiAccountTie,
  mdiAccountTieHat,
  mdiAccountTieWoman,
  mdiArrowRightBold,
  mdiAutorenew,
  mdiBarcode,
  mdiBagPersonal,
  mdiBagSuitcase,
  mdiBowTie,
  mdiBoxingGlove,
  mdiCartOutline,
  mdiCash,
  mdiCashFast,
  mdiCashRegister,
  mdiChevronRight,
  mdiCircle,
  mdiClose,
  mdiCloseCircle,
  mdiCloseCircleOutline,
  mdiCloudCheckVariant,
  mdiCoatRack,
  mdiCog,
  mdiDelete,
  mdiEmailOutline,
  mdiEye,
  mdiEyeOff,
  mdiFaceMask,
  mdiFormatListBulletedSquare,
  mdiGlasses,
  mdiHanger,
  mdiHatFedora,
  mdiInformation,
  mdiLockOutline,
  mdiMagnify,
  mdiMinus,
  mdiNecklace,
  mdiPackageVariantClosed,
  mdiPause,
  mdiPlus,
  mdiPurse,
  mdiRing,
  mdiShoeSneaker,
  mdiSunglasses,
  mdiTie,
  mdiTruck,
  mdiTshirtCrew,
  mdiTshirtCrewOutline,
  mdiUmbrella,
  mdiUnderwearOutline,
  mdiWallet,
  mdiWatch,
  mdiWeatherNight,
  mdiWeatherSunny,
} from "@mdi/js";
import { h } from "vue";

const iconPaths: Record<string, string> = {
  "mdi-account": mdiAccount,
  "mdi-account-multiple": mdiAccountMultiple,
  "mdi-account-tie": mdiAccountTie,
  "mdi-account-tie-hat": mdiAccountTieHat,
  "mdi-account-tie-woman": mdiAccountTieWoman,
  "mdi-arrow-right-bold": mdiArrowRightBold,
  "mdi-autorenew": mdiAutorenew,
  "mdi-barcode": mdiBarcode,
  "mdi-bag-personal": mdiBagPersonal,
  "mdi-bag-suitcase": mdiBagSuitcase,
  "mdi-bow-tie": mdiBowTie,
  "mdi-boxing-glove": mdiBoxingGlove,
  "mdi-cart-outline": mdiCartOutline,
  "mdi-cash": mdiCash,
  "mdi-cash-fast": mdiCashFast,
  "mdi-cash-register": mdiCashRegister,
  "mdi-chevron-right": mdiChevronRight,
  "mdi-circle": mdiCircle,
  "mdi-close": mdiClose,
  "mdi-close-circle": mdiCloseCircle,
  "mdi-close-circle-outline": mdiCloseCircleOutline,
  "mdi-cloud-check-variant": mdiCloudCheckVariant,
  "mdi-coat-rack": mdiCoatRack,
  "mdi-cog": mdiCog,
  "mdi-delete": mdiDelete,
  "mdi-email-outline": mdiEmailOutline,
  "mdi-eye": mdiEye,
  "mdi-eye-off": mdiEyeOff,
  "mdi-face-mask": mdiFaceMask,
  "mdi-format-list-bulleted-square": mdiFormatListBulletedSquare,
  "mdi-glasses": mdiGlasses,
  "mdi-hanger": mdiHanger,
  "mdi-hat-fedora": mdiHatFedora,
  "mdi-information": mdiInformation,
  "mdi-lock-outline": mdiLockOutline,
  "mdi-magnify": mdiMagnify,
  "mdi-minus": mdiMinus,
  "mdi-necklace": mdiNecklace,
  "mdi-package-variant-closed": mdiPackageVariantClosed,
  "mdi-pause": mdiPause,
  "mdi-plus": mdiPlus,
  "mdi-purse": mdiPurse,
  "mdi-ring": mdiRing,
  "mdi-shoe-sneaker": mdiShoeSneaker,
  "mdi-sunglasses": mdiSunglasses,
  "mdi-tie": mdiTie,
  "mdi-truck": mdiTruck,
  "mdi-tshirt-crew": mdiTshirtCrew,
  "mdi-tshirt-crew-outline": mdiTshirtCrewOutline,
  "mdi-umbrella": mdiUmbrella,
  "mdi-underwear-outline": mdiUnderwearOutline,
  "mdi-wallet": mdiWallet,
  "mdi-watch": mdiWatch,
  "mdi-weather-night": mdiWeatherNight,
  "mdi-weather-sunny": mdiWeatherSunny,
};

const mdi = {
  component: (props: any) => {
    const path = iconPaths[props.icon];
    if (!path) {
      console.warn(`Icon "${props.icon}" not found in custom MDI icon set`);
      return h(props.tag, null, props.icon);
    }
    return h(props.tag, null, {
      default: () => [
        h(
          "svg",
          {
            xmlns: "http://www.w3.org/2000/svg",
            viewBox: "0 0 24 24",
            role: "img",
            "aria-hidden": "true",
            class: "v-icon__svg",
          },
          [h("path", { d: path })],
        ),
      ],
    });
  },
};

const aliases: Record<string, string> = {
  collapse: "mdi-chevron-up",
  complete: "mdi-check-circle",
  cancel: "mdi-close-circle",
  close: "mdi-close",
  delete: "mdi-close-circle",
  clear: "mdi-close-circle",
  success: "mdi-check-circle",
  info: "mdi-information",
  warning: "mdi-alert-circle",
  prev: "mdi-chevron-left",
  next: "mdi-chevron-right",
  checkboxOn: "mdi-checkbox-marked",
  checkboxOff: "mdi-checkbox-blank-outline",
  checkboxIndeterminate: "mdi-minus-box",
  delimiter: "mdi-circle",
  sortAsc: "mdi-arrow-up",
  sortDesc: "mdi-arrow-down",
  expand: "mdi-chevron-down",
  menu: "mdi-menu",
  subgroup: "mdi-menu-down",
  dropdown: "mdi-menu-down",
  radioOn: "mdi-radiobox-marked",
  radioOff: "mdi-radiobox-blank",
  edit: "mdi-pencil",
  ratingEmpty: "mdi-star-outline",
  ratingFull: "mdi-star",
  ratingHalf: "mdi-star-half-full",
  loading: "mdi-cached",
  first: "mdi-page-first",
  last: "mdi-page-last",
  unfold: "mdi-unfold-more-horizontal",
  file: "mdi-paperclip",
  plus: "mdi-plus",
  minus: "mdi-minus",
  calendar: "mdi-calendar",
  treeviewCollapse: "mdi-menu-down",
  treeviewExpand: "mdi-menu-right",
  tableGroupCollapse: "mdi-chevron-down",
  tableGroupExpand: "mdi-chevron-right",
  eyeDropper: "mdi-eyedropper",
  upload: "mdi-cloud-upload",
  cloud: "mdi-cloud",
  color: "mdi-palette",
};

export { aliases, mdi };
